            if game.Workspace.Map:FindFirstChild("Arena") then
                game.Workspace.Map.Arena:FindFirstChild("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
            elseif game.Workspace.Map:FindFirstChild("Quarry") then
                game.Workspace.Map.Quarry:FindFirstChild("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
            elseif game.Workspace.Map:FindFirstChild("RingOfFire") then
                game.Workspace.Map.RingOfFire:FindFirstChild("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
            elseif game.Workspace.Map:FindFirstChild("Desert") then
                game.Workspace.Map.Desert:FindFirstChild("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
            elseif game.Workspace.Map:FindFirstChild("Classic_V2") then
                game.Workspace.Map.Classic_V2:FindFirstChild("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
            elseif game.Workspace.Map:FindFirstChild("Heaven") then
                game.Workspace.Map.Heaven:FindFirstChild("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
            elseif game.Workspace.Map:FindFirstChild("Height_Fight") then
                game.Workspace.Map.Height_Fight:FindFirstChild("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
            elseif game.Workspace.Map:FindFirstChild("WinterCountryside") then
                game.Workspace.Map.WinterCountryside:FindFirstChild("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
            elseif game.Workspace.Map:FindFirstChild("Enchanted_Desert") then
                game.Workspace.Map.Enchanted_Desert:FindFirstChild("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
            elseif game.Workspace.Map:FindFirstChild("PolarExpress") then
                game.Workspace.Map.PolarExpress:FindFirstChild("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
            elseif game.Workspace.Map:FindFirstChild("Grassy_Classic") then
                game.Workspace.Map.Grassy_Classic:FindFirstChild("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
            elseif game.Workspace.Map:FindFirstChild("Ocean") then
                game.Workspace.Map.Ocean:FindFirstChild("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
            elseif game.Workspace.Map:FindFirstChild("Underworld") then
                game.Workspace.Map.Underworld:FindFirstChild("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
            else
            print("ko thay map")
            end
