if game.Workspace.Map:GetChildren("Arena") then
    game.Workspace.Map.Arena:GetChildren("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
elseif game.Workspace.Map:GetChildren("Quarry") then
    game.Workspace.Map.Quarry:GetChildren("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
elseif game.Workspace.Map:GetChildren("RingOfFire") then
    game.Workspace.Map.RingOfFire:GetChildren("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
elseif game.Workspace.Map:GetChildren("Desert") then
    game.Workspace.Map.Desert:GetChildren("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
elseif game.Workspace.Map:GetChildren("Classic_V2") then
    game.Workspace.Map.Classic_V2:GetChildren("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
elseif game.Workspace.Map:GetChildren("Heaven") then
    game.Workspace.Map.Heaven:GetChildren("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
elseif game.Workspace.Map:GetChildren("Height_Fight") then
    game.Workspace.Map.Height_Fight:GetChildren("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
elseif game.Workspace.Map:GetChildren("WinterCountryside") then
    game.Workspace.Map.WinterCountryside:GetChildren("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
elseif game.Workspace.Map:GetChildren("Enchanted_Desert") then
    game.Workspace.Map.Enchanted_Desert:GetChildren("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
elseif game.Workspace.Map:GetChildren("PolarExpress") then
    game.Workspace.Map.PolarExpress:GetChildren("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
elseif game.Workspace.Map:GetChildren("Grassy_Classic") then
    game.Workspace.Map.Grassy_Classic:GetChildren("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
elseif game.Workspace.Map:GetChildren("Ocean") then
    game.Workspace.Map.Ocean:GetChildren("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
elseif game.Workspace.Map:GetChildren("Underworld") then
    game.Workspace.Map.Underworld:GetChildren("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
elseif game.Workspace.Map:GetChildren("Jungle") then
    game.Workspace.Map.Jumgle:GetChildren("Sock").CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
else
print("ko thay map")
end
